# Generated by Django 4.2.14 on 2024-08-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_created_at_alter_article_status_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('more', 'More Recommended'), ('less', 'Less Recommended')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.topic')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendation',
                'ordering': ['-created_at'],
            },
        ),
    ]
