# Generated by Django 4.2.14 on 2024-08-30 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Author Follow', 'verbose_name_plural': 'Author Follows'},
        ),
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pin', 'verbose_name_plural': 'Pins'},
        ),
        migrations.AlterModelOptions(
            name='readinghistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reading History', 'verbose_name_plural': 'Reading Histories'},
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'followee'), name='unique_author_follow'),
        ),
        migrations.AddConstraint(
            model_name='readinghistory',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_reading_history'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
        migrations.AlterModelTable(
            name='pin',
            table='pin',
        ),
        migrations.AlterModelTable(
            name='readinghistory',
            table='reading_history',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
