# Generated by Django 4.2.14 on 2024-08-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_alter_follow_options_alter_pin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
