# Generated by Django 4.2.14 on 2024-08-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topics',
            new_name='topic_ids',
        ),
    ]
