# Generated by Django 4.2.14 on 2024-08-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='topic_ids',
            new_name='topics',
        ),
    ]
