# Generated by Django 4.2.14 on 2024-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_created_at_alter_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish'), ('trash', 'Deleted')], default='pending', max_length=7),
        ),
    ]
