# Generated by Django 4.2.14 on 2024-08-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_comment_unique_together_comment_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
