# Generated by Django 4.2.14 on 2024-08-28 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0018_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'db_table': 'favorite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='clap',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topicfollow',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='clap',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_clap'),
        ),
        migrations.AddConstraint(
            model_name='topicfollow',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_follow'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='articles.article'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_favorite'),
        ),
    ]
