# Generated by Django 4.2.14 on 2024-08-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_remove_clap_unique_clap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clap',
            name='updated_at',
        ),
    ]
