# Generated by Django 4.2.14 on 2024-08-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_clap_count_clap_unique_clap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clap',
            name='count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
