# Generated by Django 4.2.14 on 2024-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_alter_article_author_alter_article_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('publish', 'Publish'), ('trash', 'Deleted'), ('archive', 'Archived')], default='pending', max_length=7),
        ),
    ]
