# Generated by Django 4.2.14 on 2024-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicfollow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Topic Follow', 'verbose_name_plural': 'Topic Follows'},
        ),
        migrations.RemoveConstraint(
            model_name='topicfollow',
            name='unique_follow',
        ),
        migrations.AddConstraint(
            model_name='topicfollow',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_topic_follow'),
        ),
        migrations.AlterModelTable(
            name='topicfollow',
            table='topic_follow',
        ),
    ]
