# Generated by Django 4.2.14 on 2024-08-30 18:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
